---
- name: create directory for selenium
  win_file:
    dest: "{{ selenium_dir }}"
    state: directory
    owner: IEUser

- name: download selenium
  become: false
  win_get_url:
    url: "{{ download_url }}"
    dest: "{{ selenium_dir }}/selenium-server.jar"

- name: download selenium driver for IE
  become: false
  win_get_url:
    url: "{{ iedriver_url }}"
    dest: "{{ selenium_dir }}/{{ iedriver_name }}"


- name: copy ugly batchfile
  win_copy:
    src: se_node.bat
    dest: "{{ selenium_dir }}/se_node.bat"

- name: unpack selenium driver
  script: iedriver.ps1

#- name: launch selenium with the ugly batch file
#  script: se_node.bat
